/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Models.Product;
import Utils.Tools;
import Utils.XFile;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thnrg
 */
public class ProductService extends javax.swing.JFrame {
    protected ArrayList<Product> products = new ArrayList<>();
    
    /**
     * Creates new form SanPhamService
     */
    public ProductService() {
        initComponents();
        onRun();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblProductID = new javax.swing.JLabel();
        lblProductName = new javax.swing.JLabel();
        lblProductPrice = new javax.swing.JLabel();
        txtProductID = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtProductName = new javax.swing.JTextField();
        btnLoad = new javax.swing.JButton();
        txtProductPrice = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnFakeData = new javax.swing.JButton();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý sản phẩm");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("QUẢN LÝ SẢN PHẨM");

        lblProductID.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblProductID.setText("Mã sản phẩm:");

        lblProductName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblProductName.setText("Tên sản phẩm:");

        lblProductPrice.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblProductPrice.setText("Giá:");

        btnSave.setText("Ghi file");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnLoad.setText("Mở file");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnFakeData.setText("Fake data");
        btnFakeData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFakeDataActionPerformed(evt);
            }
        });

        lblSearch.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSearch.setText("Tìm kiếm:");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduct);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtProductPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtProductID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtProductName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLoad))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdd))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch)
                        .addGap(3, 3, 3)
                        .addComponent(btnFakeData)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProductID)
                    .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProductName)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProductPrice)
                    .addComponent(txtProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFakeData)
                    .addComponent(lblSearch)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if(readForm() != null)
        {
            products.add(readForm());
            JOptionPane.showMessageDialog(this, "Thêm thành công!", "Information", JOptionPane.INFORMATION_MESSAGE);
            loadToTable();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnFakeDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFakeDataActionPerformed
        products = (ArrayList<Product>) XFile.readObject("src/Files/FakeData.dat");
        if(products == null){products = new ArrayList<>();}
        loadToTable();
    }//GEN-LAST:event_btnFakeDataActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        ArrayList<Product> filteredProducts = findNames(txtSearch.getText());
        if(!filteredProducts.isEmpty())
        {
            loadToTable(filteredProducts);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Không tìm thấy tên sản phẩm!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        saveToFile();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        loadToList();
    }//GEN-LAST:event_btnLoadActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        saveToFile();
        System.out.println("File saved successfully");
    }//GEN-LAST:event_formWindowClosing

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductMouseClicked
        if(tblProduct.getSelectedRow() != -1)
        {
            writeForm(products.get(tblProduct.getSelectedRow()));
        }
        
    }//GEN-LAST:event_tblProductMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        updateProduct();
        loadToTable();
    }//GEN-LAST:event_btnUpdateActionPerformed

    public void updateProduct()
    {
        int index = findID(txtProductID.getText());
        if(index != -1)
        {
            products.set(index, new Product(txtProductID.getText(), txtProductName.getText(), Double.valueOf(txtProductPrice.getText())));
            JOptionPane.showMessageDialog(this, "Sửa thành công", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Không tìm thấy mã sản phẩm!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    public Product readForm()
    {   
        if(isEmptyFieldWarning(txtProductID, "Mã sản phẩm không được để trống!")){return null;}
        if(isProductIDMatched(txtProductID, "Mã sản phẩm không được trùng!")){return null;}
        if(isEmptyFieldWarning(txtProductName, "Tên sản phẩm không được để trống!")){return null;}
        if(isEmptyFieldWarning(txtProductPrice, "Giá sản phẩm không được để trống!")){return null;}
        if(isPriceInvalidWarning(txtProductPrice, "Giá phải là số nguyên!", "Giá không được là số âm!")){return null;}
        
        return new Product(txtProductID.getText(), txtProductName.getText(), Double.valueOf(txtProductPrice.getText()));
    }
    
    public void writeForm(Product product)
    {
        txtProductID.setText(product.getProductID());
        txtProductName.setText(product.getProductName());
        txtProductPrice.setText(product.getProductPrice().toString());
    }
    
    public boolean isEmptyFieldWarning(JTextField txtField, String message)
    {
        if(txtField.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, message, "Warning", JOptionPane.WARNING_MESSAGE);
            txtField.requestFocus();
            return true;
        }
        return false;
    }
    
    public boolean isPriceInvalidWarning(JTextField txtField, String nanWarning, String negativeWarning)
    {
        if(!Tools.isDouble(txtField.getText()))
        {
            JOptionPane.showMessageDialog(this, nanWarning, "Warning", JOptionPane.WARNING_MESSAGE);
            txtField.requestFocus();
            return true;
        }
        if(Double.parseDouble(txtField.getText()) < 0)
        {
            JOptionPane.showMessageDialog(this, negativeWarning, "Warning", JOptionPane.WARNING_MESSAGE);
            txtField.requestFocus();
            return true;
        }
        return false;
    }
    
    public boolean isProductIDMatched(JTextField txtField, String message)
    {
        if(findID(txtField.getText()) != -1)
        {
            JOptionPane.showMessageDialog(this, message, "Warning", JOptionPane.WARNING_MESSAGE);
            txtField.requestFocus();
            return true;
        }
        return false;
    }
    
    public int findID(String id)
    {
        for(Product product: products)
        {
            if(product.getProductID().equalsIgnoreCase(id))
            {
                return products.indexOf(product);
            }
        }
        return -1;
    }
    
    public int findName(String name)
    {
        for(Product product: products)
        {
            if(product.getProductName().equalsIgnoreCase(name))
            {
                return products.indexOf(product);
            }
        }
        return -1;
    }
    
    public ArrayList<Product> findNames(String name)
    {
        ArrayList<Product> filteredProducts = new ArrayList<>();
        
        for(Product product: products)
        {
            if(product.getProductName().toLowerCase().contains(name.toLowerCase()))
            {
                filteredProducts.add(product);
            }
        }
        return filteredProducts;
    }
    
    private void onRun()
    {
        loadToList();
        loadToTable();
        if(tblProduct.getRowCount() >= 3)
        {
            writeForm(products.get(2));
        }
    }
    
    public void saveToFile()
    {
        XFile.writeObject("src/Files/Product.dat", products);
    }
    
    public void loadToList()
    {
        products = (ArrayList<Product>) XFile.readObject("src/Files/Product.dat");
        if(products == null){products = new ArrayList<>();}
    }
    
    public void loadToTable()
    {
        DefaultTableModel tbl = (DefaultTableModel) tblProduct.getModel();
        tbl.setRowCount(0);
        
        for(Product product: products)
        {
            tbl.addRow(new Object[] {product.getProductID(), product.getProductName(), product.getProductPrice()});
        }
        
        tblProduct.setModel(tbl);
    }
    
    public void loadToTable(ArrayList<Product> arrList)
    {
        DefaultTableModel tbl = (DefaultTableModel) tblProduct.getModel();
        tbl.setRowCount(0);
        
        for(Product product: arrList)
        {
            tbl.addRow(new Object[] {product.getProductID(), product.getProductName(), product.getProductPrice()});
        }
        
        tblProduct.setModel(tbl);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatLightLaf.setup();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnFakeData;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblProductID;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblProductPrice;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTextField txtProductID;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtProductPrice;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
